//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_ChungTu> tb_ChungTu { get; set; }
        public virtual DbSet<tb_Chungtu_CT> tb_Chungtu_CT { get; set; }
        public virtual DbSet<tb_CongTy> tb_CongTy { get; set; }
        public virtual DbSet<tb_DonVi> tb_DonVi { get; set; }
        public virtual DbSet<tb_DonViTinh> tb_DonViTinh { get; set; }
        public virtual DbSet<tb_HangHoa> tb_HangHoa { get; set; }
        public virtual DbSet<tb_NhaCC> tb_NhaCC { get; set; }
        public virtual DbSet<tb_NhomHH> tb_NhomHH { get; set; }
        public virtual DbSet<tb_Param> tb_Param { get; set; }
        public virtual DbSet<tb_Qlban> tb_Qlban { get; set; }
        public virtual DbSet<tb_SYS_Function> tb_SYS_Function { get; set; }
        public virtual DbSet<tb_SYS_Group> tb_SYS_Group { get; set; }
        public virtual DbSet<tb_SYS_report> tb_SYS_report { get; set; }
        public virtual DbSet<tb_SYS_Right> tb_SYS_Right { get; set; }
        public virtual DbSet<tb_SYS_Right_Rep> tb_SYS_Right_Rep { get; set; }
        public virtual DbSet<tb_SYS_SEQUENCE> tb_SYS_SEQUENCE { get; set; }
        public virtual DbSet<tb_SYS_User> tb_SYS_User { get; set; }
        public virtual DbSet<tb_TONKHO> tb_TONKHO { get; set; }
        public virtual DbSet<tb_XuatXu> tb_XuatXu { get; set; }
        public virtual DbSet<R_CHUNGTU> R_CHUNGTU { get; set; }
        public virtual DbSet<V_Chungtu_CT> V_Chungtu_CT { get; set; }
        public virtual DbSet<v_Func_SYS_Right> v_Func_SYS_Right { get; set; }
        public virtual DbSet<V_rep_sys_right_rep> V_rep_sys_right_rep { get; set; }
        public virtual DbSet<V_user_in_gr> V_user_in_gr { get; set; }
        public virtual DbSet<v_user_not_in_group> v_user_not_in_group { get; set; }
    
        [DbFunction("Entities", "FN_DOANHTHU_THEOMATHANG")]
        public virtual IQueryable<FN_DOANHTHU_THEOMATHANG_Result> FN_DOANHTHU_THEOMATHANG(Nullable<System.DateTime> nGAYD, Nullable<System.DateTime> nGAYC)
        {
            var nGAYDParameter = nGAYD.HasValue ?
                new ObjectParameter("NGAYD", nGAYD) :
                new ObjectParameter("NGAYD", typeof(System.DateTime));
    
            var nGAYCParameter = nGAYC.HasValue ?
                new ObjectParameter("NGAYC", nGAYC) :
                new ObjectParameter("NGAYC", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_DOANHTHU_THEOMATHANG_Result>("[Entities].[FN_DOANHTHU_THEOMATHANG](@NGAYD, @NGAYC)", nGAYDParameter, nGAYCParameter);
        }
    
        [DbFunction("Entities", "FN_DOANHTHU_THEONHOMHANG")]
        public virtual IQueryable<FN_DOANHTHU_THEONHOMHANG_Result> FN_DOANHTHU_THEONHOMHANG(Nullable<System.DateTime> nGAYD, Nullable<System.DateTime> nGAYC)
        {
            var nGAYDParameter = nGAYD.HasValue ?
                new ObjectParameter("NGAYD", nGAYD) :
                new ObjectParameter("NGAYD", typeof(System.DateTime));
    
            var nGAYCParameter = nGAYC.HasValue ?
                new ObjectParameter("NGAYC", nGAYC) :
                new ObjectParameter("NGAYC", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_DOANHTHU_THEONHOMHANG_Result>("[Entities].[FN_DOANHTHU_THEONHOMHANG](@NGAYD, @NGAYC)", nGAYDParameter, nGAYCParameter);
        }
    
        public virtual int REP_TONKHO_DVI(Nullable<System.DateTime> nGAYD, Nullable<System.DateTime> nGAYC, string mADVI)
        {
            var nGAYDParameter = nGAYD.HasValue ?
                new ObjectParameter("NGAYD", nGAYD) :
                new ObjectParameter("NGAYD", typeof(System.DateTime));
    
            var nGAYCParameter = nGAYC.HasValue ?
                new ObjectParameter("NGAYC", nGAYC) :
                new ObjectParameter("NGAYC", typeof(System.DateTime));
    
            var mADVIParameter = mADVI != null ?
                new ObjectParameter("MADVI", mADVI) :
                new ObjectParameter("MADVI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REP_TONKHO_DVI", nGAYDParameter, nGAYCParameter, mADVIParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<SP_DOANHTHU_THEOMATHANG_Result> SP_DOANHTHU_THEOMATHANG(Nullable<System.DateTime> nGAYD, Nullable<System.DateTime> nGAYC)
        {
            var nGAYDParameter = nGAYD.HasValue ?
                new ObjectParameter("NGAYD", nGAYD) :
                new ObjectParameter("NGAYD", typeof(System.DateTime));
    
            var nGAYCParameter = nGAYC.HasValue ?
                new ObjectParameter("NGAYC", nGAYC) :
                new ObjectParameter("NGAYC", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DOANHTHU_THEOMATHANG_Result>("SP_DOANHTHU_THEOMATHANG", nGAYDParameter, nGAYCParameter);
        }
    
        public virtual ObjectResult<SP_DOANHTHU_THEONHOMHANG_Result> SP_DOANHTHU_THEONHOMHANG(Nullable<System.DateTime> nGAYD, Nullable<System.DateTime> nGAYC)
        {
            var nGAYDParameter = nGAYD.HasValue ?
                new ObjectParameter("NGAYD", nGAYD) :
                new ObjectParameter("NGAYD", typeof(System.DateTime));
    
            var nGAYCParameter = nGAYC.HasValue ?
                new ObjectParameter("NGAYC", nGAYC) :
                new ObjectParameter("NGAYC", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DOANHTHU_THEONHOMHANG_Result>("SP_DOANHTHU_THEONHOMHANG", nGAYDParameter, nGAYCParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int spNGAY_TINHTON(ObjectParameter nGAYC, ObjectParameter nGAYD, ObjectParameter nAM, ObjectParameter kY)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNGAY_TINHTON", nGAYC, nGAYD, nAM, kY);
        }
    
        public virtual int TINH_TONKHO_DONVI(Nullable<System.DateTime> nGAYC, string mADVI)
        {
            var nGAYCParameter = nGAYC.HasValue ?
                new ObjectParameter("NGAYC", nGAYC) :
                new ObjectParameter("NGAYC", typeof(System.DateTime));
    
            var mADVIParameter = mADVI != null ?
                new ObjectParameter("MADVI", mADVI) :
                new ObjectParameter("MADVI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TINH_TONKHO_DONVI", nGAYCParameter, mADVIParameter);
        }
    }
}
