//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_CHUNGTU
    {
        public System.Guid KHOA { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string SoChungTu { get; set; }
        public string SoChungTu2 { get; set; }
        public Nullable<System.DateTime> NGAY2 { get; set; }
        public Nullable<int> LoaiCT { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public Nullable<double> SOLUONG { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string GHICHU { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public string MADVI2 { get; set; }
        public Nullable<int> Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public Nullable<int> Delete_By { get; set; }
    }
}
