//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChungTu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ChungTu()
        {
            this.tb_Chungtu_CT = new HashSet<tb_Chungtu_CT>();
        }
    
        public System.Guid Khoa { get; set; }
        public string SoChungTu { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string SoChungTu2 { get; set; }
        public Nullable<System.DateTime> Ngay2 { get; set; }
        public Nullable<int> LoaiCT { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string GhiChu { get; set; }
        public string MaCty { get; set; }
        public string MaDVI { get; set; }
        public string MaDVI2 { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Create_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<int> Update_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public Nullable<int> Delete_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Chungtu_CT> tb_Chungtu_CT { get; set; }
        public virtual tb_DonVi tb_DonVi { get; set; }
    }
}
