//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Chungtu_CT
    {
        public System.Guid KhoaCT { get; set; }
        public Nullable<System.Guid> Khoa { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> SoluongCT { get; set; }
        public Nullable<double> Dongia { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> idban { get; set; }
        public Nullable<double> Thanhtien { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<double> Chietkhau { get; set; }
        public Nullable<int> Stt { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual tb_ChungTu tb_ChungTu { get; set; }
        public virtual tb_HangHoa tb_HangHoa { get; set; }
        public virtual tb_Qlban tb_Qlban { get; set; }
    }
}
