//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HangHoa
    {
        public string BarCode { get; set; }
        public string TenHH { get; set; }
        public string TenTat { get; set; }
        public string DVT { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string MaNCC { get; set; }
        public Nullable<int> Maxuatxu { get; set; }
        public string IdNhom { get; set; }
        public string Mota { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Create_By { get; set; }
        public Nullable<bool> Disable { get; set; }
    }
}
