//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HangHoa()
        {
            this.tb_Chungtu_CT = new HashSet<tb_Chungtu_CT>();
        }
    
        public string BarCode { get; set; }
        public string TenHH { get; set; }
        public string TenTat { get; set; }
        public string DVT { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string MaNCC { get; set; }
        public Nullable<int> Maxuatxu { get; set; }
        public string IdNhom { get; set; }
        public string Mota { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Create_By { get; set; }
        public Nullable<bool> Disable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Chungtu_CT> tb_Chungtu_CT { get; set; }
        public virtual tb_NhaCC tb_NhaCC { get; set; }
        public virtual tb_NhomHH tb_NhomHH { get; set; }
        public virtual tb_XuatXu tb_XuatXu { get; set; }
    }
}
