//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Param
    {
        public int id { get; set; }
        public string Macty { get; set; }
        public string Madvi { get; set; }
        public string TenCty { get; set; }
        public string TenDvi { get; set; }
    }
}
