//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Qlban
    {
        public int idban { get; set; }
        public string tenban { get; set; }
        public Nullable<int> sokhach { get; set; }
        public Nullable<bool> trangthai { get; set; }
    }
}
