//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SYS_report
    {
        public int Rep_code { get; set; }
        public string Description { get; set; }
        public string Rep_name { get; set; }
        public Nullable<bool> Visibled { get; set; }
        public Nullable<bool> TuNgay { get; set; }
        public Nullable<bool> Thangnam { get; set; }
        public Nullable<bool> Macty { get; set; }
        public Nullable<bool> madvi { get; set; }
        public Nullable<bool> tonkho { get; set; }
    }
}
