//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Chungtu_CT
    {
        public System.Guid Khoa { get; set; }
        public string SoChungTu { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string SoChungTu2 { get; set; }
        public Nullable<System.DateTime> Ngay2 { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string GhiChu { get; set; }
        public string MaCty { get; set; }
        public string MaDVI { get; set; }
        public string MaDVI2 { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Create_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<int> Update_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public Nullable<int> Delete_By { get; set; }
        public System.Guid KhoaCT { get; set; }
        public string Barcode { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public Nullable<double> Dongia { get; set; }
        public Nullable<double> Thanhtien { get; set; }
        public Nullable<System.DateTime> Expr2 { get; set; }
        public Nullable<int> Stt { get; set; }
    }
}
