//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Func_SYS_Right
    {
        public string FUNC_Code { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public string Parent { get; set; }
        public int Sort { get; set; }
        public int Iduser { get; set; }
        public string quyen { get; set; }
    }
}
