//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_rep_sys_right_rep
    {
        public int Rep_code { get; set; }
        public string Description { get; set; }
        public string Rep_name { get; set; }
        public Nullable<bool> Visibled { get; set; }
        public int Iduser { get; set; }
        public string QUYEN { get; set; }
    }
}
