//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_user_in_gr
    {
        public Nullable<int> Iduser { get; set; }
        public string Username { get; set; }
        public string Passwd { get; set; }
        public string Fullname { get; set; }
        public string Macty { get; set; }
        public string Madvi { get; set; }
        public Nullable<System.DateTime> Last_PWD_Changed { get; set; }
        public Nullable<bool> Disable { get; set; }
        public Nullable<bool> Isgroup { get; set; }
        public int id { get; set; }
        public int Group { get; set; }
        public int Iduser_in_gr { get; set; }
    }
}
